### ISSUE TITLE
Cant get it to work.

### ISSUE THREAD

**Issue by ghost** [marcusvb/r710-fancontroller#1]
After installing and trying to run the service I see if keeps failing with an error "ZeroDivisionError: division by zero". Then i noticed it was using MegaCLI to pull the HDD Temps. I installed MegaCLI on the ubuntu sever i am running this on but no luck.  I'm not versed enough in python to tweak it myself. I'm sure this is one of those issues staring me right in the face I'm just at a loss.

**Comment by clinkadink** [comment]
Make sure you can manually run megacli first .... if not, this is how I installed it:

wget --user=hetzner --password=download http://download.hetzner.de/tools/LSI/tools/MegaCLI/8.07.14_MegaCLI.zip
unzip 8.07.14_MegaCLI.zip -d megacli
cd megacli/Linux
sudo alien MegaCli-8.07.14-1.noarch.rpm
sudo dpkg -i megacli_8.07.14-2_all.deb
sudo ln -s /opt/MegaRAID/MegaCli/MegaCli64 /usr/bin/megacli

**Comment by marcusvb** [comment]
@clinkadink is absolutely correct. The divide by zero error appears due to no data being able to be fetched by megacli. I've also tested it without megacli and I can recreate the issue. 

Installing megacli and checking if you can run it manually is a solution to the issue. Megacli is a dependency for the script.
